version: 0.2
phases: null
install: null
runtime-versions: null
golang: 1.14
build: null
commands:
  - echo Building the Go code...
  - go build avg.go
artifacts: null
secondary-artifacts: null
golang_artifacts: null
base-directory: newdemo.git
files: '-avg'
